name: contextsv
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - htslib
  - swig
  - pytest
  - plotly
  - pandas
  - scikit-learn>=1.3
  - joblib

# conda env create --name contextsv --file environment.yml
