{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set revision = environ.get('GIT_FULL_HASH') %}

package:
  name: contextsv
  version: {{ version }}

source:
  path: ../
  git_lfs: false

channels:
  - conda-forge
  - bioconda
  - defaults

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - htslib=1.20
  run:
    - htslib=1.20

test:
    commands:
        - contextsv --help
        - test -f $PREFIX/bin/contextsv
        - contextsv --version
about:
  home: https://github.com/WGLab/ContextSV
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Long-read structural variant caller'
  description: |
    ContextSV is a tool for calling structural variants from long read
    sequencing data that integrates important copy number and single-nucleotide
    allele frequency information to improve accuracy.
  dev_url: https://github.com/WGLab/ContextSV
  doc_url: https://github.com/WGLab/ContextSV#readme
