name: contextsvmerge
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pytest
  - plotly
  - pandas
  - scikit-learn>=1.3

# conda env create --name contextsvmerge --file environment.yml
