name: build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download assets
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: 'WGLab/ContextSV'
        version: 'tags/v0.1.0'
        file: 'SampleData.zip'

    - name: Unzip assets
      shell: bash --login {0}
      run: unzip SampleData.zip -d tests/data

    - name: Set up conda (Miniconda only)
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Configure conda channels and create environment
      shell: bash -l {0}
      run: |
        conda config --remove channels defaults || true
        conda config --add channels conda-forge
        conda config --add channels bioconda
        conda config --set channel_priority strict
        conda info  # confirm the change
        conda env create -f environment.yml

    - name: Build C++ code
      shell: bash --login {0}  # --login enables PATH variable access
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate contextsv
        echo "CONDA_PREFIX=$CONDA_PREFIX"
        ls -l $CONDA_PREFIX/include/htslib
        make CONDA_PREFIX=$CONDA_PREFIX

    - name: Test installation
      shell: bash --login {0}
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate contextsv
        ./build/contextsv --version
        ./build/contextsv --help

    - name: Run tests
      shell: bash --login {0}
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate contextsv
        mkdir -p output
        python -m pytest -s -v

      # run: |
      #   source $(conda info --base)/etc/profile.d/conda.sh
      #   conda activate contextsv
      #   mkdir -p tests/output
      #   python -m pytest -s -v tests/test_general.py
