name: build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download assets
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: 'WGLab/ContextSV'
        version: 'tags/v0.1.0'
        file: 'TestData.zip'

    - name: Unzip assets
      shell: bash --login {0}
      run: unzip TestData.zip

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: contextsv
        environment-file: environment.yml
        python-version: 3.10
        auto-activate-base: false

    - name: Install samtools and bcftools using sudo apt-get
      run: |
        sudo apt-get update
        sudo apt-get install -y samtools bcftools

    - name: Build C++ code
      shell: bash --login {0}  # --login enables PATH variable access
      run: |
        make

    - name: Run unit tests
      shell: bash --login {0}
      run: |
        mkdir -p tests/output
        python -m pytest -s -v tests/test_general.py
