name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - 2-alignment-based-sv-calling

jobs:
    api-doc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Build docs
              run: doxygen Doxyfile
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/html
